version: '3'
services: 
    nginx:
        restart: always #make sure that nginx is always on!
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '4000:80'
        depends_on: 
            - api
            - client
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis: 
        image: 'redis:latest'
    api: 
        build:
            dockerfile: Dockerfile.dev # specify only the name of the Dockerfile to execute
            context: ./server # specify the location of the above file 
        volumes:
            - /app/node_module # keep this folder inside of the container as it is; don't try to override it
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379